FROM golang:1.22.0-alpine3.19
ARG glpat
ARG gituser
WORKDIR /root
RUN \
  apk update 
RUN \  
  apk add git build-base

RUN \
  git clone -b neutron_client https://${gituser}:${glpat}@github.com/WassimDhib/kubernetes-cluster-autoscaler.git  && \
  cd kubernetes-cluster-autoscaler && \
  go mod download github.com/gophercloud/gophercloud && \
  go mod download github.com/gophercloud/utils && \
  go mod download golang.org/x/crypto && \
  go mod tidy && \
  go build -o autoscaler  cmd/main.go


FROM golang:1.22.0-alpine3.19
WORKDIR /go/bin
COPY --from=0 /root/kubernetes-cluster-autoscaler/autoscaler .
CMD ["./autoscaler"]
